language: node_js
sudo: required
node_js:
  - "8"
  - "6"
  - "4"
env:
  global:
    - NODE_TLS_REJECT_UNAUTHORIZED=0
    - INTRAVENOUS=yes
script: "npm test"
services:
  - mongodb
  - redis-server
addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server